// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcxvbysoevfgbszzncoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjeHZieXNvZXZmZ2JzenpuY29pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjM3MDcsImV4cCI6MjA2NDY5OTcwN30.shzUH4w_kTO3MxRLok-WDXhv8QwqHkbai_t9kgRc6mQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);